name: Compilar Jogo PS2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: h4570/tyra:latest
    steps:
      - uses: actions/checkout@v4

      - name: Executar Compilacao
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Baixar o arquivo ELF pronto
        uses: actions/upload-artifact@v4
        with:
          name: meu-jogo-elf
          path: build/amongus.elf
